import {
    sexyBaccaratImage,
    yeebetLiveImage,
    gameplayInteractiveImage,
    afb777Image,
    wCasinoImage,
    bigGamingImage,
    dreamGamingImage,
    allbetImage,
    veryGoodImage,
    saGamingImage,
    ct855Image,
    pragmaticPlayImage,
    ezugiMenuTile,
    playtechCasinoTile,
    afbGamingMenuTile,
} from './liveCasinoMenuTileAssets';

/** @see `liveCasinoMenuTileAssets.js` — images must live under `src/assets/live-casino/`. */
export const defaultLiveCasinoNavProviders = [
    { id: 'sexy-gaming', name: 'Sexy Baccarat', image: sexyBaccaratImage, hot: true },
    { id: 'yeebet-live', name: 'YB Live', image: yeebetLiveImage, hot: true },
    { id: 'big-gaming', name: 'Big Gaming', image: bigGamingImage, hot: true },
    { id: 'playtech', name: 'Playtech', image: playtechCasinoTile, hot: true },
    { id: 'dream-gaming', name: 'DreamGaming', image: dreamGamingImage, hot: true },
    { id: 'pragmatic-play', name: 'Pragmatic Play', image: pragmaticPlayImage, hot: true },
    { id: 'ezugi', name: 'Ezugi', image: ezugiMenuTile, hot: true },
    { id: 'afb-gaming', name: 'AFB Gaming', image: afbGamingMenuTile, hot: true },
    { id: 'sagaming', name: 'SA Gaming', image: saGamingImage, hot: true },
    { id: 'evolution', name: 'CT855', image: ct855Image, hot: false },
    { id: 'allbet', name: 'AllBet', image: allbetImage, hot: false },
    { id: 'world-entertainment', name: 'Gameplay Interactive', image: gameplayInteractiveImage, hot: false },
    { id: 'casino', name: 'W Casino', image: wCasinoImage, hot: false },
    { id: 'mt-live', name: 'Very Good', image: veryGoodImage, hot: false },
];
